services:
  back-end:
    container_name: finance-code-back-end
    depends_on:
      - db
    command: npm run dev
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end/src:/back-end/src
      - ./back-end/app.js:/back-end/app.js
      - ./back-end/package.json:/back-end/package.json
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}

  front-end:
    container_name: finance-code-front-end
    command: npm run start
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules
    ports:
      - "3000:3000"
    build:
      context: ./front-end

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
